/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ingsw;

import javax.swing.JOptionPane;

/**
 *
 * @author Marco
 */
public class SchermataInserimentoStruttura extends javax.swing.JFrame {

    private ControllerSchermate controller;
    private String NomeStruttura;
    private String Indirizzo;
    private String Categoria;
    private String Prezzo;
    
    /**
     * Creates new form SchermataInserimentoStruttura
     */
    public SchermataInserimentoStruttura() {
        initComponents();
    }
    
    public SchermataInserimentoStruttura(ControllerSchermate controller) {
        initComponents();
        this.controller = controller;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        IntestazioneLabel = new javax.swing.JLabel();
        NomeStrutturaLabel = new javax.swing.JLabel();
        IndirizzoLabel = new javax.swing.JLabel();
        CategoriaLabel = new javax.swing.JLabel();
        PrezzoLabel = new javax.swing.JLabel();
        IndietroButton = new javax.swing.JButton();
        AvantiButton = new javax.swing.JButton();
        NomeStrutturaField = new javax.swing.JTextField();
        IndirizzoField = new javax.swing.JTextField();
        CategoriaBox = new javax.swing.JComboBox<>();
        PrezzoBox = new javax.swing.JComboBox<>();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        CittaLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        IntestazioneLabel.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        IntestazioneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IntestazioneLabel.setText("Inserisci i dati della nuova struttura");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(IntestazioneLabel, gridBagConstraints);

        NomeStrutturaLabel.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        NomeStrutturaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomeStrutturaLabel.setText("Nome della struttura");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        getContentPane().add(NomeStrutturaLabel, gridBagConstraints);

        IndirizzoLabel.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        IndirizzoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IndirizzoLabel.setText("Indirizzo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        getContentPane().add(IndirizzoLabel, gridBagConstraints);

        CategoriaLabel.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        CategoriaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CategoriaLabel.setText("Categoria");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        getContentPane().add(CategoriaLabel, gridBagConstraints);

        PrezzoLabel.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        PrezzoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PrezzoLabel.setText("Range di prezzo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        getContentPane().add(PrezzoLabel, gridBagConstraints);

        IndietroButton.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        IndietroButton.setText("Indietro");
        IndietroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IndietroButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.2;
        getContentPane().add(IndietroButton, gridBagConstraints);

        AvantiButton.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        AvantiButton.setText("Avanti");
        AvantiButton.setEnabled(false);
        AvantiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvantiButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.2;
        getContentPane().add(AvantiButton, gridBagConstraints);

        NomeStrutturaField.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        NomeStrutturaField.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                IndirizzoFieldMouseMoved(evt);
            }
        });
        NomeStrutturaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IndirizzoFieldKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.3;
        getContentPane().add(NomeStrutturaField, gridBagConstraints);

        IndirizzoField.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        IndirizzoField.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                IndirizzoFieldMouseMoved(evt);
            }
        });
        IndirizzoField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IndirizzoFieldKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.3;
        getContentPane().add(IndirizzoField, gridBagConstraints);

        CategoriaBox.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        CategoriaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ristorante", "Hotel", "Parco", "Bar", "Teatro", "Museo" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 0.3;
        getContentPane().add(CategoriaBox, gridBagConstraints);

        PrezzoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "€", "€€", "€€€" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 0.3;
        getContentPane().add(PrezzoBox, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.weightx = 0.9;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(filler1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(filler2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(filler3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(filler4, gridBagConstraints);

        CittaLabel.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        CittaLabel.setText("Città");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        getContentPane().add(CittaLabel, gridBagConstraints);

        jTextField1.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.3;
        getContentPane().add(jTextField1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AvantiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvantiButtonActionPerformed
        if (IndirizzoField.getText().equals("") || NomeStrutturaField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "I campi Indirizzo e Nome Struttura non possono essere vuoti!");
        }
        else {
            this.setVisible(false);
            controller.showInserisciFoto();
        }
    }//GEN-LAST:event_AvantiButtonActionPerformed

    private void IndietroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IndietroButtonActionPerformed
        this.setVisible(false);
        controller.showGestioneStrutture();
    }//GEN-LAST:event_IndietroButtonActionPerformed

    private void IndirizzoFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IndirizzoFieldKeyPressed
        if (IndirizzoField.getText().equals("") || NomeStrutturaField.getText().equals("")) {
            AvantiButton.setEnabled(false);
        } else {
            AvantiButton.setEnabled(true);
        }
    }//GEN-LAST:event_IndirizzoFieldKeyPressed

    private void IndirizzoFieldMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IndirizzoFieldMouseMoved
        if (IndirizzoField.getText().equals("") || NomeStrutturaField.getText().equals("")) {
            AvantiButton.setEnabled(false);
        } else {
            AvantiButton.setEnabled(true);
        }
    }//GEN-LAST:event_IndirizzoFieldMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchermataInserimentoStruttura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchermataInserimentoStruttura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchermataInserimentoStruttura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchermataInserimentoStruttura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchermataInserimentoStruttura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AvantiButton;
    private javax.swing.JComboBox<String> CategoriaBox;
    private javax.swing.JLabel CategoriaLabel;
    private javax.swing.JLabel CittaLabel;
    private javax.swing.JButton IndietroButton;
    private javax.swing.JTextField IndirizzoField;
    private javax.swing.JLabel IndirizzoLabel;
    private javax.swing.JLabel IntestazioneLabel;
    private javax.swing.JTextField NomeStrutturaField;
    private javax.swing.JLabel NomeStrutturaLabel;
    private javax.swing.JComboBox<String> PrezzoBox;
    private javax.swing.JLabel PrezzoLabel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
