/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ingsw;

import java.io.File;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Marco
 */
public class SchermataSelezionaFoto extends javax.swing.JFrame {

    private SchermataInserisciFoto CaricaFoto;
    private SchermataModificaStruttura ModificaFoto;
    
    public SchermataSelezionaFoto() {
        initComponents();
        this.setLocationRelativeTo(null);    
        FileFilter filter = new FileNameExtensionFilter("File immagini", "jpg", "jpeg", "png", "bmp");
        jFileChooser1.setAcceptAllFileFilterUsed(false);
        jFileChooser1.addChoosableFileFilter(filter);
        jFileChooser1.setFileFilter(filter);
    }
    
    public SchermataSelezionaFoto(SchermataModificaStruttura ModificaFoto) {
        initComponents();
        this.setLocationRelativeTo(null);
        CaricaFoto = null;
        this.ModificaFoto = ModificaFoto;        
        FileFilter filter = new FileNameExtensionFilter("File immagini", "jpg", "jpeg", "png", "bmp");
        jFileChooser1.setAcceptAllFileFilterUsed(false);
        jFileChooser1.addChoosableFileFilter(filter);
        jFileChooser1.setFileFilter(filter);
        try {
                UIManager.setLookAndFeel(UIManager
                        .getSystemLookAndFeelClassName());
            } catch (ClassNotFoundException | InstantiationException
                    | IllegalAccessException | UnsupportedLookAndFeelException e) {
                e.printStackTrace();
            }
    }
    
    public SchermataSelezionaFoto(SchermataInserisciFoto CaricaFoto) {
        initComponents();
        this.setLocationRelativeTo(null);
        ModificaFoto = null;
        this.CaricaFoto = CaricaFoto;        
        FileFilter filter = new FileNameExtensionFilter("File immagini", "jpg", "jpeg", "png", "bmp");
        jFileChooser1.setAcceptAllFileFilterUsed(false);
        jFileChooser1.addChoosableFileFilter(filter);
        jFileChooser1.setFileFilter(filter);
        try {
                UIManager.setLookAndFeel(UIManager
                        .getSystemLookAndFeelClassName());
            } catch (ClassNotFoundException | InstantiationException
                    | IllegalAccessException | UnsupportedLookAndFeelException e) {
                e.printStackTrace();
            }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jFileChooser1.setDialogTitle("Seleziona una foto");
        jFileChooser1.setFileFilter(null);
        jFileChooser1.setName(""); // NOI18N
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });
        getContentPane().add(jFileChooser1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        if(CaricaFoto != null) {
            CaricaFoto.setFoto(jFileChooser1.getSelectedFile());
            this.setVisible(false);
            CaricaFoto.setVisible(true);
        } else if(ModificaFoto != null) {
            ModificaFoto.modificaFoto(jFileChooser1.getSelectedFile());
            this.setVisible(false);
    }
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
}
